#! /bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
nc='\033[0m'

echo -e '
____________            _____           _ _    _ _
|  _  \ ___ \          |_   _|         | | |  (_) |
| | | | |_/ /  ______    | | ___   ___ | | | ___| |_
| | | |  __/  |______|   | |/ _ \ / _ \| | |/ / | __|
| |/ /| |                | | (_) | (_) | |   <| | |_
|___/ \_|                \_/\___/ \___/|_|_|\_\_|\__|v1.0
@Norseman2018
'

printf "\n"

echo -e "${GREEN}1 - Stealth Scan"
echo -e "2 - Start Das-Schcanner"
echo -e "3 - Common Port scan"
echo -e "4 - Enable/disable Local web Server"
echo -e "5 - NBT scan"
echo -e "6 - ARP Scan"
echo -e "7 - FPING scan"
echo -e "8 - HOST's ALIVE${nc}"

printf "\n"

read -p "Please Choose from one of the options by entering the number: " option

printf "\n"

echo "You selected option:" $option

printf "\n"

if [ $option == 1 ]
then
        echo -e " [+]${CYAN} Starting Stealth Scan ${nc}[+] "
        printf "\n"
        read -p "What is the IP address or Range: " ipaddress;
        printf "\n";
        sudo nmap -sS -Pn -n $ipaddress -T4 -oN stealth.txt

elif [ $option == 2 ]
then
        echo -e " [+]${CYAN} Starting Das-Schcanner ${nc}[+] "
        ./das-schcanner.sh

elif [ $option == 3 ]
then
        echo -e " [+]${CYAN} Starting Common Port Scan ${nc}[+] "
        printf "\n"
        read -p "What is the IP address or Range: " ipaddress;
        printf "\n"
        nmap -sSV -p 21,22,23,25,80,443,445 $ipaddress

elif [ $option == 4 ]
then
        echo -e " [+]${CYAN} Checking if Apache2 is installed ${nc}[+] "
        web="which apache2"
        x=$(eval $web)
        if [ $x == "/usr/sbin/apache2" ]
        then
                printf "\n"
                echo "Enabling Apache now"
                printf "\n"
                service apache2 start
                echo -e " [+]${CYAN} Apache Server Enabled ${nc}[+] "
                echo "Your IP address is the following: "
                ifconfig | grep 'inet [0-9].'
                printf "\n"
        else
                printf "\n"
                echo " !!! Apache2 is not installed please type the following to install: "
                printf "\n"
                echo "sudo apt-get install apache2 -y"
        fi

elif [ $option == 5 ]
then
        read -p "What is the IP address or IP Range you wish to scan: " ipaddress;
        printf "\n"
        echo -e " [+]${CYAN} Starting the NBT Scan ${nc}[+] "
        printf "\n"
        sudo nbtscan -r $ipaddress

elif [ $option == 6 ]
then
        read -p "What is the IP address or IP Range you wish to scan: " ipaddress;
        printf "\n"
        echo -e " [+]${CYAN} Starting the ARP scan ${nc}[+] "
        printf "\n"
        sudo arp-scan -I eth0 $ipaddress

elif [ $option == 7 ]
then
        read -p "What is the IP address or the IP Range you wish to scan: " ipaddress;
        printf "\n"
        echo -e "${CYAN} [+] Starting the FPING scan ${nc}[+] "
        printf "\n"
        sudo fping -agqs -r 1 $ipaddress

elif [ $option == 8 ]
then
        read -p "Enter IP addresses to check seperated by spaces (e.g 10.0.0.1 10.1.1.0 10.1.2.1: " ipcount;
        for ip in $ipcount; do
                ping -c 2 $ip
        done

else
        echo "Unknown choice was selected"

fi
